version: '2.2'

services:
  mongo:
    restart: always
    image: mongo:4.0
    expose:
        - 27017

  roborally:
    restart: always
    build: .
    ports:
        - 3000:3000
    depends_on:
        - mongo
    environment:
        - MONGO_URL=mongodb://localhost:27017/roborally
        - ROOT_URL=http://localhost:3000
